export const GO_TO_HOME = ( navigate ) => navigate( '/' )
export const GO_TO_LOGIN = ( navigate ) => navigate( '/entrar' )
export const GO_TO_SIGNUP = ( navigate ) => navigate( '/cadastro' )
export const GO_TO_CART = ( navigate ) => navigate( '/carrinho' )
export const GO_TO_FAVORITES = ( navigate ) => navigate( '/favoritos' )